name: Trigger CodePipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Check if pipeline exists
        run: |
          if aws codepipeline get-pipeline --name FotoApp6-Pipeline --region eu-west-1; then
            echo "Pipeline exists"
          else
            echo "Pipeline does not exist"
            aws codepipeline list-pipelines --region eu-west-1
            exit 1
          fi

      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name FotoApp6-Pipeline \
            --region eu-west-1
